### ISSUE TITLE
`DOWNLOAD_STATIC_LIBV8` alpine version

### ISSUE THREAD

**Issue by kklot** [jeroen/V8#115]
Is it possible to provide a static version compiled on `alpine` linux with this option? I think the two versions provided were compiled  with `glibc` which does not work on `alpine` (error such as `__fprintf_chk  not found`).

**Comment by jeroen** [comment]
Not yet. I could try to build one, this is what I used : https://github.com/jeroen/build-v8-static

**Comment by jeroen** [comment]
Which version of alpine do you use?

**Comment by kklot** [comment]
I use [latest](https://hub.docker.com/_/alpine) tag, so it should be `3`, not sure the `edge` tag would have any benefits in compiling.

**Comment by jeroen** [comment]
Should work now, can you try pls

**Comment by kklot** [comment]
Thanks, I tempted to try that new code in `jeroen/build-v8-static` but too complicated for me. But now how should I install `V8` with that one? still failed on `alpine:latest` image below (ran `DOWNLOAD_STATIC_LIBV8=1; install.packages("V8")` after open the image sh).   
```
FROM alpine:latest
RUN apk add R-dev R-doc R git libxml2-dev musl-dev g++
```

**Comment by jeroen** [comment]
This works for me in R on alpine:

```r
Sys.setenv(DOWNLOAD_STATIC_LIBV8=1)
install.packages("V8")
```

**Comment by kklot** [comment]
Sorry, it works, I missed `Sys.setenv`.
